language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.3

cache:
  directories:
    - $HOME/.composer/cache

install: composer install

script: vendor/bin/phpstan analyse

notifications:
  email: false
